<?php $date = $block->quote->getDeliveryDate(); ?>
<script>
    require([
        "jquery",
        "jquery/ui",
        'uiRegistry'
    ], function($, ui, registry){
        registry.set('Oye_Deliverydate_initDatepicker', function(element)
        {
            var beforeShowDay = function(date)
            {
                var excludeWeekdays = [<?php echo $block->helper->getConfigExcludedWeekdays(); ?>];

                var holidays = [];
                //holidays with * as year will get current and next year, become two holidays
                <?php foreach ($block->getHolidays() as $holiday): ?>
                holidays.push(<?php echo strtotime($holiday) * 1000; ?> ); //? http://stackoverflow.com/questions/10837022/convert-php-date-into-javascript-date-format
                <?php endforeach; ?>

                function checkHolidays(date, holidays)
                {
                    var result = true;
                    $.each(holidays, function(index, holiday){
                        var holiday = new Date(holiday);
                        if(isDateEqual(date, holiday))
                        {
                            result = false;
                        }
                    });
                    return result;
                }

                function checkWeekdays(date, excludeWeekdays)
                {
                    return $.inArray(date.getDay(), excludeWeekdays) == -1;
                }

                function isDateEqual(date1, date2)
                {
                    return date1.setHours(0,0,0,0) == date2.setHours(0,0,0,0);
                }

                var result =    checkHolidays(date, holidays) && checkWeekdays(date, excludeWeekdays);
                return [result, ''];
            };

            var minDate = <?php echo $block->helper->getConfigMinDelayDays(); ?>;
            if(minDate == 0)
            {
                if(<?php echo json_encode($block->helper->isDisableAfterSameDayTime()) ?>)
                {
                    minDate = 1;
                }
            }

            if($(element).length > 0)
            {
                $(element).datepicker(
                    {
                        minDate : minDate,
                        maxDate : <?php echo $block->helper->getConfigMaxDelayDays(); ?>,
                        dateFormat: "<?php echo $block->convertDateFormatToJQueryUi($block->helper->getConfigDateFormat()); ?>",
                        beforeShowDay : beforeShowDay
                    }
                );
            }
            else
            {
                return {
                    minDate : minDate,
                    maxDate : <?php echo $block->helper->getConfigMaxDelayDays(); ?>,
                    dateFormat: "<?php echo $block->convertDateFormatToJQueryUi($block->helper->getConfigDateFormat()); ?>",
                    beforeShowDay : beforeShowDay,
                    <?php if($date && $date != '0000-00-00 00:00:00'):?> //set date if it was saved in quote before
                    defaultDate : new Date(Date.parse('<?php echo $date ?>'.replace('-','/','g')))
                    <?php endif; ?>
                };
            }
        });
    });
</script>