<div class="admin__field order-create-field">
    <label class="label admin__field-label">
        <span>Delivery Date</span>
    </label>
    <input
        type="text"
        id="delivery-date"
        name="delivery-date"
        class="admin__control-text"
        value="<?php echo $block->getStoredDeliveryDate(); ?>"
        >
</div>


<script>
    require([
        'jquery',
        'uiRegistry'
    ], function($, registry){

        var initFunction = registry.get('Oye_Deliverydate_initDatepicker');
        var delveryDate = $('#delivery-date');
        initFunction(delveryDate);

        $(delveryDate).on('change', function(event)
        {
            order.loadArea(['shipping_method'], true, {delivery_date : $('#delivery-date').val()});
        });
    });
</script>